#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

DIR=$(dirname $0)

. "$DIR/common"
. "$DIR/ozone-common"

function start {
  if [[ ! -e "$NODE_DIR/data/ozone/scm/current/VERSION" ]]; then
    ozone scm --init 1</dev/null
  fi
  do_start ozone scm

  # Wait for SCM to exit safe mode
  TRIES=3 # 30 sec for each try
  while ! ozone admin safemode wait -t 30 >& /dev/null; do
    printf "."
    if [ ${TRIES} -le 0 ]; then
      echo "Failed to start SCM"
      return 1
    fi
    TRIES=`expr ${TRIES} - 1`
  done
  echo "SCM started"
  return 0
}

$1
